[package]
name = "riffol"
version = "0.1.0"
authors = ["John Hedges <john@drystone.co.uk>"]
build = "build.rs"

[dependencies]
chan-signal = "0.3"
libc = "0.2"
nereon = "0.1"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
syslog = "4.0"